### ISSUE TITLE
Close sessions still opened

### ISSUE THREAD

**Issue by Delor3an** [owncloud/administration#105]
Hi,

A simple button to close all sessions still opened but not the current one in use to prevent disconnection on click in Personnal > Username.

For the moment (OwnCloud 9.1.3) we can only close sessions one by one. Really, really long...

Systems like iOS doesn't close properly the connection on CardDAV/CalDAV

Thanks by advance, don't hesitate to ask for any further questions

**Comment by kdslkdsaldsal** [comment]
@Delor3an Unfortunately you're at the wrong at this issue tracker. The correct one would be https://github.com/owncloud/core/issues

Please close here and re-open a new one at the link above. Please also make sure that you're filling out the issue template shown there as its not really clear what your issue is.
