### ISSUE TITLE
Update server entry for 10.0.9

### ISSUE THREAD

**Issue by PVince81** [owncloud/administration#154]
@VicDeo can you adjust the update server config ?

I wonder if we should write a script that updates the config automatically and pushes a PR...

cc @davitol @hodyroff

**Comment by VicDeo** [comment]
@PVince81 https://github.com/owncloud/administration/pull/140 was about easier and faster release process, as  the topmost part of`config.php` would contain only non-EOL major versions; it is currently OC 10 only.

Right now I need to scroll here and there due to duplication between the channels - they all contain complete update path from 6 to 10.
