### ISSUE TITLE
Web Installer Redesign

### ISSUE THREAD

**Issue by aspdye** [owncloud/administration#63]
According to: https://github.com/owncloud/core/issues/21356

**Comment by jancborchardt** [comment]
@aspdye good call!

@PVince81 @DeepDiver1975 can we simply reuse the template here? @aspdye you can definitely just copy the styles to make it look like the current installation page to get this started. :)

**Comment by karlitschek** [comment]
A refreshed design is a good idea. It is important that the installer is only one file. So all needed styles and photos have to be hosted on owncloud.org. Is uggest to use new files,urls for the new styles so that the old installer still looks correct.

**Comment by DeepDiver1975** [comment]
From a pure technical pov - a fusion of installer and updater would be great.

We "simply" need to find a solution to full-fill the one-file-requirement - web phar might be a solution ...

Web phar requires basically two files - the phar and a starter script which requires the phar
see http://www.sitepoint.com/packaging-your-apps-with-phar/

**Comment by karlitschek** [comment]
yes. combining this might be cool. on the other hand this installer is quite simple and works. so no sure merging this makes a lot of things better. :-)

**Comment by DeepDiver1975** [comment]
Well maintaining one tool instead of two ... ;-)

**Comment by jancborchardt** [comment]
Both installing and updating is functionality people expect. If technically it makes sense to combine them, we should go for it. (I can not say a lot about that except that even my measly shell scripts for setting up and updating ownCloud are almost the same …)

And it would make sure that both processes – which are unfortunately always a pain to test and done too little – run more smoothly since we don’t have to fix stuff in two places.

**Comment by karlitschek** [comment]
Let's keep is separate please. The installer is working fine and the updater is already complex enough. Let's concentrate our time in implementing all the features and usecases in the updater please. Thanks

**Comment by hitam4450** [comment]
@karlischeck :thumbsup:
